version: '2'

services:

    telegraf:
        image: telegraf:alpine
        volumes:
          - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
          - /var/run/docker.sock:/var/run/docker.sock
        privileged: true
        restart: always

