version: '2'

services:

    influxdb:
        image: influxdb:alpine
        ports:
          - "8083:8083"
          - "8086:8086"
          - "8089:8089"
        volumes:
          - /srv/data/influxdb:/var/lib/influxdb
          - ./ssl/influxdb.pem:/etc/ssl/influxdb.pem
          #- ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
        environment:
          - INFLUXDB_HTTP_AUTH_ENABLED=true
          - INFLUXDB_ADMIN_HTTPS_ENABLED=true
          - INFLUXDB_HTTP_HTTPS_ENABLED=true

